global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: load_balancer
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names: [ "load_balancer" ]
        type: "A"
        port: 8082

  - job_name: mcp
    honor_timestamps: true
    metrics_path: /metrics
    dns_sd_configs:
      - names: [ "mcp" ]
        type: "A"
        port: 8080