<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
  </PropertyGroup>
  <ItemGroup Label="Analyzer">
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
    <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="4.14.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.117" />
  </ItemGroup>
  <ItemGroup Label="Mcp">
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="1.4.0" />
  </ItemGroup>
  <ItemGroup Label="Application">
    <PackageVersion Include="Mapster" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup Label="Domain">
    <PackageVersion Include="JacksonVeroneze.NET.Result" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup Label="Infrastructure">
    <PackageVersion Include="CorrelationId" Version="3.0.1" />
    <PackageVersion Include="Mapster.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.16.0-beta.1" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.16.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.16.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.16.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Process" Version="1.16.0-rc.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageVersion Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageVersion Include="Serilog.Expressions" Version="5.0.0" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="14.0.1" />
    <PackageVersion Include="Refit.Reflection" Version="14.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.8.0" />
  </ItemGroup>
  <ItemGroup Label="Tests">
    <PackageVersion Include="FluentAssertions" Version="7.2.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
</Project>